### ISSUE TITLE
一直登陆超时

### ISSUE THREAD

**Issue by changanshichangan** [HuanMeng233/weread_downloader#4]
一直登陆超时，重新登陆后还是超时
<img width="227" alt="屏幕截图 2023-12-14 195106" src="https://github.com/HuanMeng233/weread_downloader/assets/98247068/ada33c18-aa4c-44f5-98a5-562739d330e2">

**Comment by HuanMeng233** [comment]
可以下载一下debug版本，看一下命令行里面的日志

**Comment by changanshichangan** [comment]
DEB | Using go webview2loader
开始下载 3300060259
获取书籍信息请求Url https://i.weread.qq.com/book/info?bookId=3300060259&myzy=1&source=reading&teenmode=0
获取书籍信息返回状态码 401
-1 0
下载请求Url https://i.weread.qq.com/book/chapterdownload?bookId=3300060259&chapters=0--1&pf=wechat_wx-2001-android-100-weread&pfkey=pfKey&zoneId=1&bookVersion=0&bookType=&quote=&release=1&stopAutoPayWhenBNE=1&preload=2&preview=0&offline=0&giftPayingCard=0&enVersion=7.5.0&modernVersion=7.5.0&teenmode=0
下载请求返回状态码 401
下载请求返回body {"errcode":-2012,"errlog":"C5Iu7E3","errmsg":"登录超时"}

**Comment by changanshichangan** [comment]
我好像大概弄明白了这个问题，大概是因为我是使用微信读书软件来扫码登录的，所以才会导致登录超时，今天重新登录了微信，用微信扫码是可以下载的。
