### ISSUE TITLE
算出来的密码是错的，解压不了zip文件

### ISSUE THREAD

**Issue by WangDongYao** [HuanMeng233/weread_downloader#6]
Mac下wails build之后，把应用复制到桌面后，直接运行里面的可执行文件，可以下载文件，但提示读取文件失败，看了下日志打印，`flate: corrupt input before offset 1`，然后直接测试pwd解压zip，也是失败的，是不是密码算法换了？

**Comment by HuanMeng233** [comment]
> Mac下wails build之后，把应用复制到桌面后，直接运行里面的可执行文件，可以下载文件，但提示读取文件失败，看了下日志打印，`flate: corrupt input before offset 1`，然后直接测试pwd解压zip，也是失败的，是不是密码算法换了？

我试了下win还可以，mac的情况我不清楚。

你可以试试打印出 
![image](https://github.com/HuanMeng233/weread_downloader/assets/53157970/e43e7b80-ecb9-445b-b0d9-e0bbe8d15861)
下载请求返回头的encryptKey
![image](https://github.com/HuanMeng233/weread_downloader/assets/53157970/ea8d4d53-b7a7-4486-9051-4880d4db8b26)
手动用这两个方法算一下密码

**Comment by WangDongYao** [comment]
还是不行，我用iOS抓包，直接导出抓到的zip包，用算法算出密码也解压不了，用的是master分支，代码应该是最新的吧？

**Comment by HuanMeng233** [comment]
> 还是不行，我用iOS抓包，直接导出抓到的zip包，用算法算出密码也解压不了，用的是master分支，代码应该是最新的吧？ 比如下载的这本呼兰河传：
> 
> ```
> 开始下载 785704
> 200
> 49 0 txt
> URL https://i.weread.qq.com/book/chapterdownload?bookId=785704&chapters=0-49&pf=wechat_wx-2001-android-100-weread&pfkey=pfKey&zoneId=1&bookVersion=0&bookType=txt&quote=&release=1&stopAutoPayWhenBNE=1&preload=2&preview=0&offline=0&giftPayingCard=0&enVersion=7.5.0&modernVersion=7.5.0&teenmode=0
> encryptKey t9IoQEnPbhCX0LHcjYOL+A==
> pwd U[dwg*Wy
> flate: corrupt input before offset 7
> ```

试了一下，这本书我也下不了。 回头我研究下

**Comment by x-pyrrhus** [comment]
> 我用iOS抓包，直接导出抓到的zip包，用算法算出密码也解压不了，用的是master分支，代码应该是最新

大佬解决了吗，我iOS抓包获取参数，再用`code getPassword(vid string, encryptKey string)` 方法获取出来的密码也是解压不了
