### ISSUE TITLE
能否将HTML 转为epub

### ISSUE THREAD

**Issue by changanshichangan** [HuanMeng233/weread_downloader#7]
开发你好，https://github.com/cyhhao/html2epub
这是一个将html转为epub的项目，不知道能否将输出文件转为epub来更加适合在移动端阅读呢，还有就是由于本项目在飞机上已经传播开来，需不需要将本想项目进行伪装。

**Comment by WangDongYao** [comment]
感觉可以直接抄一下作业，参考一下dd电子书的合成代码，https://github.com/yann0917/dedao-dl

**Comment by WangDongYao** [comment]
发现xhtml里面的图片还是在线请求微信服务器的，这个得处理一下，否则没办法离线查看。例如
`<div class="bodyPic"><img active="true" alt="" src="https://res.weread.qq.com/wrepub/CB_3300063607_image00217.jpg" data-w="1280px" data-ratio="0.285" data-w-new="365px" style="width:100%;" /></div>`
